### ISSUE TITLE
Remove unnecessary comments from acli.py

### ISSUE THREAD

**Issue by danishprakash** [prakashdanish/amizone-cli#1]
Remove unnecessary comments from acli.py specifically at lines #34 #35 and #45

They were added for testing and debugging and should now be removed so as to avoid confusion amongst readers.

**Note:** This issue is for first-time contributors only.

**Comment by niharikakrishnan** [comment]
Since the contributing.md file says to first discuss before contributing to the repository, is it okay if I take this up?

**Comment by heisendumb** [comment]
#7

**Comment by danishprakash** [comment]
@niharikakrishnan thanks for actually taking the time for reading it up. However, I think you have relevant experience and this issue seems rather trivial for you. Good thing that you took the time to discuss instead of blindly sending a PR for such a trivial task. 

You should look at other issues which are more suited to you. Good Luck 😄
